### ISSUE TITLE
Implementar Serviço Rest para Turma Formanda

### ISSUE THREAD

**Issue by 7robertodantas** [MeFormei/backend#1]
Definir um serviço rest para as informações das turmas. Exemplo de modelagem:

```json

"turma": {

  "nome": "Unkown Exception",

  "ano": "2017.1",

  "imagem": "http://imagem.com/turma/1.jpg",

  "curso": "Tecnologia da Informação",

  "coordenador": {"nome": "Gustavo Girão",
		"thumbnail":"gustavo.jpg"},   

  "orador": {"nome":"Lucio Soares",
		"thumbnail": "lucio.jpg"},

  "juramentista": {"nome":"Fabiana Silva",
  		"thumbnail": "fabiana.jpg"},

  "patrono":  {"nome":"Silvia Silva",
  		"thumbnail": "silvia.jpg"},

  "parainfo":  {"nome":"Ivanovich Silva", 
  		"thumbnail": "ivanovich.jpg"},

  "professoresHomenageados": [

    {"nome":"Adja Andrade", 
      "thumbnail": "adja.jpg"},

    {"nome":"Gustavo Girão",
      "thumbnail": "gustavo.jpg"},

    {"nome":"Carlos Eduardo",
      "thumbnail": "carlos.jpg"},

  ], 

  "comissao": [

    {"nome":"Rubens Paiva",
      "responsabilidade":"Presidente",
      "thumbnail": "rubens.jpg"},

    {"nome":"Ana Caroline",
      "responsabilidade":"Vice-Presidente",
      "thumbnail": "ana.jpg"},

    {"nome":"Fernanda Chacon",
      "responsabilidade":"Coordenador de Eventos/Arrecadações",
      "thumbnail": "fernanda.jpg"},

    {"nome":"Hugo André",
      "responsabilidade":"Secretário",
      "thumbnail": "hugo.jpg"},

  ],

  "formandos": [

   {"nome":"Ciro Martins",
     "ingresso":"2013.1",
     "matricula":"2013018973",
     "email":"cirom96@gmail.com",
     "frase":"Se a vida te der limões, faça limonada", 
     "thumbnail":"ciro.jpg"},

   {"nome":"Lucas Cristiano",
     "ingresso":"2013.1",
     "matricula":"2013020908",
     "email":"lucascristiano27@gmail.com",
     "frase":"Off The Shelf", 
     "thumbnail":"lucas.jpg"},


  ]
  
}

```

**Comment by 7robertodantas** [comment]
Removi algumas informações que considero não relevantes para esse primeiro momento.
- De aluno: "Enfase" acredito que não seja necessário pois no fim, a turma corresponde a um único curso curso, nesse caso não é considerado a ênfase. (todas as ênfases de BTI, no final das contas se tornam, Bacharelado em Tecnologia da Informação. Além disso, não é todo curso que possui ênfase)

- De homenageados: "Tipo", removi pois a organização do schema json já está agrupado por tipos, que serão utilizados nas telas.

- Da turma: "Instituição" removi pois até o momento é visado utilizar turmas de uma mesma instituição.

- Vice Coordenador e Diretor removi pois existem diversos outros diretores, se for adicionar um acredito que tenha q colocar os outros também.

Informações que é válido incluir no schema da issue:
- Link para Lattes (apesar de não achar muito usual pois o usuário teria que anotar o link em um papel já que o sistema não irá dispor desse tipo de navegação na web)

- Reitor, pode ser algo válido possuir essa informação.

Adicionei Matricula e Ingresso pois achei que pudesse ser interessante.

Mas como disse, a issue está aberta a discussão para chegarmos a um consenso final

**Comment by JuhCrln** [comment]
Como exemplo tá ok, mas juramentista, orador e comissão acho desnecessários.

**Comment by victoprincipe** [comment]
Iremos usar o esquema da foto que Alan postou para essa sprint.
